name: Memoet blog
description: Notes about learning on the web
meta_description: "Notes about learning on the web: spaced repetition, web development"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: /blog/
domain_name: "https://memoetapp.github.io/blog/"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://memoetapp.github.io/blog/"
author: "Memoet team"
